/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author dnlal
 */
public class EditStateFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditStateFrame
     */
    public EditStateFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlState = new javax.swing.JPanel();
        TextoSignupLabel = new javax.swing.JLabel();
        btnRemoveState = new javax.swing.JButton();
        btnAddState = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        btnChangeToCity = new javax.swing.JButton();
        txtStateName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNewStateName = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnChangeName = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlState.setBackground(new java.awt.Color(255, 255, 255));
        pnlState.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextoSignupLabel.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        TextoSignupLabel.setText("Edición de estado");
        pnlState.add(TextoSignupLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 310, -1));

        btnRemoveState.setText("Eliminar");
        btnRemoveState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveStateActionPerformed(evt);
            }
        });
        pnlState.add(btnRemoveState, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 100, 30));

        btnAddState.setText("Agregar");
        btnAddState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStateActionPerformed(evt);
            }
        });
        pnlState.add(btnAddState, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 120, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        pnlState.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 210, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nombre: ");
        pnlState.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, 30));

        btnChangeToCity.setText("Ciudad");
        btnChangeToCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeToCityActionPerformed(evt);
            }
        });
        pnlState.add(btnChangeToCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 110, 30));

        txtStateName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtStateName.setForeground(new java.awt.Color(153, 153, 153));
        txtStateName.setBorder(null);
        txtStateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateNameActionPerformed(evt);
            }
        });
        pnlState.add(txtStateName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 220, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Agregar/Eliminar estado:");
        pnlState.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Nuevo nombre:");
        pnlState.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, 30));

        txtNewStateName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNewStateName.setForeground(new java.awt.Color(153, 153, 153));
        txtNewStateName.setBorder(null);
        txtNewStateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewStateNameActionPerformed(evt);
            }
        });
        pnlState.add(txtNewStateName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 250, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        pnlState.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 240, 10));

        btnChangeName.setText("Cambiar nombre");
        btnChangeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeNameActionPerformed(evt);
            }
        });
        pnlState.add(btnChangeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 130, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pnlState.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 270, 350));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Editar nombre: ");
        pnlState.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        pnlState.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlState, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlState, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveStateActionPerformed

    private void btnAddStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddStateActionPerformed

    private void btnChangeToCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeToCityActionPerformed
        EditCityFrame cityFrame = new EditCityFrame(); 
        cityFrame.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnChangeToCityActionPerformed

    private void txtStateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateNameActionPerformed

    private void txtNewStateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewStateNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewStateNameActionPerformed

    private void btnChangeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangeNameActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        EditCountryFrame countryFrame = new EditCountryFrame();
        countryFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditStateFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextoSignupLabel;
    private javax.swing.JButton btnAddState;
    private javax.swing.JButton btnChangeName;
    private javax.swing.JButton btnChangeToCity;
    private javax.swing.JButton btnRemoveState;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlState;
    private javax.swing.JTextField txtNewStateName;
    private javax.swing.JTextField txtStateName;
    // End of variables declaration//GEN-END:variables
}
