/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author dnlal
 */
public class EditCountryFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddCountryFrame
     */
    public EditCountryFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextoSignupLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnAddCountry = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNewCountry = new javax.swing.JTextField();
        btnChangeNameCountry = new javax.swing.JButton();
        btnChangeToState = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        FirstName_field2 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnRemoveCiy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextoSignupLabel.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        TextoSignupLabel.setText("Edición de país");
        jPanel1.add(TextoSignupLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 360, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        txtCountry.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCountry.setForeground(new java.awt.Color(153, 153, 153));
        txtCountry.setBorder(null);
        txtCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountryActionPerformed(evt);
            }
        });
        jPanel1.add(txtCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 220, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 210, 10));

        btnAddCountry.setText("Agregar");
        btnAddCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCountryActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 120, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nombre: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, 30));

        txtNewCountry.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNewCountry.setForeground(new java.awt.Color(153, 153, 153));
        txtNewCountry.setBorder(null);
        txtNewCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewCountryActionPerformed(evt);
            }
        });
        jPanel1.add(txtNewCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 220, 30));

        btnChangeNameCountry.setText("Cambiar nombre");
        btnChangeNameCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeNameCountryActionPerformed(evt);
            }
        });
        jPanel1.add(btnChangeNameCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 130, 30));

        btnChangeToState.setText("Estado");
        btnChangeToState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeToStateActionPerformed(evt);
            }
        });
        jPanel1.add(btnChangeToState, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 110, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Nuevo nombre:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, 30));

        FirstName_field2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        FirstName_field2.setForeground(new java.awt.Color(153, 153, 153));
        FirstName_field2.setBorder(null);
        FirstName_field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstName_field2ActionPerformed(evt);
            }
        });
        jPanel1.add(FirstName_field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 220, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 220, 10));

        btnRemoveCiy.setText("Eliminar");
        btnRemoveCiy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCiyActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemoveCiy, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 100, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Agregar/Eliminar país: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 270, 370));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Editar nombre: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountryActionPerformed

    private void btnAddCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCountryActionPerformed

    private void txtNewCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewCountryActionPerformed

    private void btnChangeNameCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeNameCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangeNameCountryActionPerformed

    private void FirstName_field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstName_field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstName_field2ActionPerformed

    private void btnChangeToStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeToStateActionPerformed
        EditStateFrame stateFrame = new EditStateFrame(); 
        stateFrame.setVisible(true); 
        this.dispose(); 
    }//GEN-LAST:event_btnChangeToStateActionPerformed

    private void btnRemoveCiyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCiyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveCiyActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Admin adminFrame = new Admin(); 
        adminFrame.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCountryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCountryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCountryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCountryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCountryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FirstName_field2;
    private javax.swing.JLabel TextoSignupLabel;
    private javax.swing.JButton btnAddCountry;
    private javax.swing.JButton btnChangeNameCountry;
    private javax.swing.JButton btnChangeToState;
    private javax.swing.JButton btnRemoveCiy;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtNewCountry;
    // End of variables declaration//GEN-END:variables
}
