/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.SignUpModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUpModel
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignUpPanel = new javax.swing.JPanel();
        lblSignUp = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        Combo_field = new javax.swing.JComboBox<>();
        lblCountry = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblState = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        lblCity = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        LastName_field = new javax.swing.JTextField();
        FirstName_field2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblEmail = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtEmail = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        FirstName_field5 = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        signUp_btn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        comboBox_año = new javax.swing.JComboBox<>();
        comboBox_dia = new javax.swing.JComboBox<>();
        comboBox_mes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SignUpPanel.setBackground(new java.awt.Color(255, 255, 255));
        SignUpPanel.setBorder(new javax.swing.border.MatteBorder(null));
        SignUpPanel.setForeground(new java.awt.Color(242, 242, 242));
        SignUpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSignUp.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        lblSignUp.setText("Registro de usuario: ");
        SignUpPanel.add(lblSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 440, -1));

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFirstName.setText("Nombre: ");
        SignUpPanel.add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        FirstName_field.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        FirstName_field.setForeground(new java.awt.Color(153, 153, 153));
        FirstName_field.setBorder(null);
        FirstName_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        SignUpPanel.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 210, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Género: ");
        SignUpPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 80, -1));

        Combo_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other", " " }));
        Combo_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_fieldActionPerformed(evt);
            }
        });
        SignUpPanel.add(Combo_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 90, 30));

        lblCountry.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCountry.setText("País:");
        SignUpPanel.add(lblCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Costa Rica", " " }));
        SignUpPanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 110, 40));

        lblState.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblState.setText("Estado: ");
        SignUpPanel.add(lblState, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San Jose", "Cartago", "Alajuela", "Puntarenas", "Heredia", "Limon", "Guanacaste" }));
        SignUpPanel.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 110, 40));

        lblCity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCity.setText("Ciudad: ");
        SignUpPanel.add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SignUpPanel.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 170, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        SignUpPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 210, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        SignUpPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 210, 10));

        lblLastName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLastName.setText("Apellido:");
        SignUpPanel.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        LastName_field.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        LastName_field.setForeground(new java.awt.Color(153, 153, 153));
        LastName_field.setBorder(null);
        LastName_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastName_fieldActionPerformed(evt);
            }
        });
        SignUpPanel.add(LastName_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 220, 20));

        FirstName_field2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        FirstName_field2.setForeground(new java.awt.Color(153, 153, 153));
        FirstName_field2.setBorder(null);
        FirstName_field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumActionPerformed(evt);
            }
        });
        SignUpPanel.add(txtPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 210, 20));

        lblPhoneNum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPhoneNum.setText("Número de telefono: ");
        SignUpPanel.add(lblPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        SignUpPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 210, 10));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Fecha de nacimiento");
        SignUpPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        SignUpPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 210, 10));

        FirstName_field4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        FirstName_field4.setForeground(new java.awt.Color(153, 153, 153));
        FirstName_field4.setBorder(null);
        FirstName_field4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        SignUpPanel.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 210, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Dirección de correo: ");
        SignUpPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        SignUpPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 290, 10));

        FirstName_field5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        FirstName_field5.setForeground(new java.awt.Color(153, 153, 153));
        FirstName_field5.setBorder(null);
        FirstName_field5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        SignUpPanel.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 290, 20));

        btnSignUp.setText("Registrarse");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        SignUpPanel.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 170, 40));

        lblFirstName1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFirstName1.setText("Fecha de nacimiento: ");
        SignUpPanel.add(lblFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, -1, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        SignUpPanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 210, 10));

        txtUsername.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtUsername.setBorder(null);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        SignUpPanel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 210, 20));

        lblLastName1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLastName1.setText("Contraseña:");
        SignUpPanel.add(lblLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, -1, 20));

        txtPassword.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPassword.setBorder(null);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        SignUpPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 210, 20));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        SignUpPanel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 210, 10));

        lblFirstName2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFirstName2.setText("Usuario:");
        SignUpPanel.add(lblFirstName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, -1, 20));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        SignUpPanel.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        signUp_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        signUp_btn.setText("Sign Up");
        signUp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUp_btnActionPerformed(evt);
            }
        });
        SignUpPanel.add(signUp_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Dirección de correo: ");
        SignUpPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        comboBox_año.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SignUpPanel.add(comboBox_año, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        comboBox_dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBox_dia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBox_diaItemStateChanged(evt);
            }
        });
        comboBox_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_diaActionPerformed(evt);
            }
        });
        SignUpPanel.add(comboBox_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        comboBox_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SignUpPanel.add(comboBox_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        jLabel2.setText("año");
        SignUpPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        jLabel3.setText("dia");
        SignUpPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel4.setText("mes");
        SignUpPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SignUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SignUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Combo_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_fieldActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void LastName_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastName_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastName_fieldActionPerformed

    private void txtPhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Login ln= new Login();
        ln.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnVolverActionPerformed

    private void signUp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUp_btnActionPerformed
       
        try {
            boolean flag;
            flag= SignUpModel.Register(FirstName_field.getText(), LastName_field.getText());
            if (flag==true){
                JOptionPane.showMessageDialog(rootPane, "Se inserto");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "No se inserto");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
                        
                  
        
        
    }//GEN-LAST:event_signUp_btnActionPerformed

    private void comboBox_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_diaActionPerformed
       
        
    }//GEN-LAST:event_comboBox_diaActionPerformed

    private void comboBox_diaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBox_diaItemStateChanged
        String[] dir = new String[31];

        for(int i = 0; i < dir.length; i++) { dir[i] = Integer.toString(i);}
        comboBox_dia.setModel(new DefaultComboBoxModel<>(dir));
        comboBox_dia.setVisible(true);
        
        
        comboBox_dia.setModel(new DefaultComboBoxModel<>(dir));
    }//GEN-LAST:event_comboBox_diaItemStateChanged

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combo_field;
    private javax.swing.JTextField FirstName_field;
    private javax.swing.JTextField FirstName_field2;
    private javax.swing.JTextField FirstName_field4;
    private javax.swing.JTextField FirstName_field5;
    private javax.swing.JTextField LastName_field;
    private javax.swing.JPanel SignUpPanel;
    private javax.swing.JLabel TextoSignupLabel;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> comboBox_año;
    private javax.swing.JComboBox<String> comboBox_dia;
    private javax.swing.JComboBox<String> comboBox_mes;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton signUp_btn;
    // End of variables declaration//GEN-END:variables


}
