/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maro
 */
public class Usuarios extends javax.swing.JFrame {
    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipalUsuarios = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        PanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        BotonInsertar = new javax.swing.JPanel();
        LabelInsertar = new javax.swing.JLabel();
        BotonModificar = new javax.swing.JPanel();
        LabelModificar = new javax.swing.JLabel();
        BotonCerrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotonConsultar = new javax.swing.JPanel();
        LabelConsultar = new javax.swing.JLabel();
        BotonEliminar = new javax.swing.JPanel();
        LabelEliminar = new javax.swing.JLabel();
        PanelActualizar = new javax.swing.JPanel();
        TextoActualizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipalUsuarios.setBackground(new java.awt.Color(204, 204, 255));
        PanelPrincipalUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelPrincipalUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTitulo.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        LabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitulo.setText("Usuarios");
        PanelPrincipalUsuarios.add(LabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 120, 40));
        LabelTitulo.getAccessibleContext().setAccessibleDescription("");

        jScrollPane1.setBorder(null);

        TablaUsuarios.setAutoCreateRowSorter(true);
        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_RegisteredUser", "Ru_Password", "Ru_Username", "Id_Person", "Id_Audit", "CreationDate", "CreationUser", "LastModificationDate", "LastModificationUser"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaUsuarios.setToolTipText("");
        TablaUsuarios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TablaUsuarios.setColumnSelectionAllowed(true);
        TablaUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaUsuarios.setName(""); // NOI18N
        TablaUsuarios.setSelectionBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.icon[filled].pressedSelectedBackground"));
        TablaUsuarios.setSelectionForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        TablaUsuarios.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        TablaUsuarios.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        TablaUsuarios.setShowGrid(true);
        TablaUsuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaUsuarios);
        TablaUsuarios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout PanelTablaLayout = new javax.swing.GroupLayout(PanelTabla);
        PanelTabla.setLayout(PanelTablaLayout);
        PanelTablaLayout.setHorizontalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        PanelTablaLayout.setVerticalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTablaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        PanelPrincipalUsuarios.add(PanelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 510, 330));

        BotonInsertar.setBackground(new java.awt.Color(204, 255, 255));
        BotonInsertar.setToolTipText("");

        LabelInsertar.setBackground(new java.awt.Color(204, 204, 255));
        LabelInsertar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelInsertar.setLabelFor(BotonInsertar);
        LabelInsertar.setText("Insertar");
        LabelInsertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout BotonInsertarLayout = new javax.swing.GroupLayout(BotonInsertar);
        BotonInsertar.setLayout(BotonInsertarLayout);
        BotonInsertarLayout.setHorizontalGroup(
            BotonInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        BotonInsertarLayout.setVerticalGroup(
            BotonInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        PanelPrincipalUsuarios.add(BotonInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 70, 30));

        BotonModificar.setBackground(new java.awt.Color(204, 255, 255));

        LabelModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelModificar.setLabelFor(BotonModificar);
        LabelModificar.setText("Modificar");
        LabelModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout BotonModificarLayout = new javax.swing.GroupLayout(BotonModificar);
        BotonModificar.setLayout(BotonModificarLayout);
        BotonModificarLayout.setHorizontalGroup(
            BotonModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        BotonModificarLayout.setVerticalGroup(
            BotonModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        PanelPrincipalUsuarios.add(BotonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        BotonCerrar.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<--");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout BotonCerrarLayout = new javax.swing.GroupLayout(BotonCerrar);
        BotonCerrar.setLayout(BotonCerrarLayout);
        BotonCerrarLayout.setHorizontalGroup(
            BotonCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        BotonCerrarLayout.setVerticalGroup(
            BotonCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        PanelPrincipalUsuarios.add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, -1));

        BotonConsultar.setBackground(new java.awt.Color(204, 255, 255));

        LabelConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelConsultar.setLabelFor(BotonConsultar);
        LabelConsultar.setText("Consultar");
        LabelConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout BotonConsultarLayout = new javax.swing.GroupLayout(BotonConsultar);
        BotonConsultar.setLayout(BotonConsultarLayout);
        BotonConsultarLayout.setHorizontalGroup(
            BotonConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        BotonConsultarLayout.setVerticalGroup(
            BotonConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        PanelPrincipalUsuarios.add(BotonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));

        BotonEliminar.setBackground(new java.awt.Color(204, 255, 255));

        LabelEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEliminar.setLabelFor(BotonEliminar);
        LabelEliminar.setText("Eliminar");
        LabelEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout BotonEliminarLayout = new javax.swing.GroupLayout(BotonEliminar);
        BotonEliminar.setLayout(BotonEliminarLayout);
        BotonEliminarLayout.setHorizontalGroup(
            BotonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        BotonEliminarLayout.setVerticalGroup(
            BotonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        PanelPrincipalUsuarios.add(BotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 70, -1));

        PanelActualizar.setBackground(new java.awt.Color(204, 255, 255));

        TextoActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoActualizar.setText("Actualizar");
        TextoActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextoActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextoActualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelActualizarLayout = new javax.swing.GroupLayout(PanelActualizar);
        PanelActualizar.setLayout(PanelActualizarLayout);
        PanelActualizarLayout.setHorizontalGroup(
            PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        PanelActualizarLayout.setVerticalGroup(
            PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        PanelPrincipalUsuarios.add(PanelActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipalUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipalUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoActualizarMouseClicked
        // TODO add your handling code here:
        Connection connection = null;
        try{
        //Se conecta a la base de datos
        Class.forName("oracle.jdbc.driver.OracleDriver");
        String dbURL = "jdbc:oracle:thin:@localhost:1521:DBPRUEBA";
        String username = "pr";
        String password = "pr";
        connection = DriverManager.getConnection(dbURL,username, password);
        Statement st = connection.createStatement();
        String sql = "Select * from RegisteredUser"; //Query para traer datos
        ResultSet rs = st.executeQuery(sql);
        while(rs.next()){
            //Se agregan los campos de la tabla como variables
            String id_RU = String.valueOf(rs.getInt("ID_REGISTEREDUSER"));
            String ru_Password = rs.getString("RU_PASSWORD");
            String ru_UserName = rs.getString("RU_USERNAME");
            String id_Person = String.valueOf(rs.getInt("ID_PERSON"));
            String id_Audit = String.valueOf(rs.getInt("Id_Audit"));
            String creationDate = String.valueOf(rs.getDate("CREATIONDATE"));
            String creationUser = rs.getString("CREATIONUSER");
            String lastModDate = String.valueOf(rs.getDate("LASTMODIFICATIONDATE"));
            String lastModUser = rs.getString("LASTMODIFICATIONUSER");
            
            String tbData[] = {id_RU,ru_Password,ru_UserName,id_Person,id_Audit,
            creationDate, creationUser, lastModDate, lastModUser }; //Ingreso las variables que tienen los datos
            DefaultTableModel tbModel = (DefaultTableModel)TablaUsuarios.getModel();
            
            tbModel.addRow(tbData); //Agrega una fila a la tabla
            }
        }
     catch (ClassNotFoundException | SQLException e){
         System.out.println(e.getMessage());
     }
         
    }//GEN-LAST:event_TextoActualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonCerrar;
    private javax.swing.JPanel BotonConsultar;
    private javax.swing.JPanel BotonEliminar;
    private javax.swing.JPanel BotonInsertar;
    private javax.swing.JPanel BotonModificar;
    private javax.swing.JLabel LabelConsultar;
    private javax.swing.JLabel LabelEliminar;
    private javax.swing.JLabel LabelInsertar;
    private javax.swing.JLabel LabelModificar;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel PanelActualizar;
    private javax.swing.JPanel PanelPrincipalUsuarios;
    private javax.swing.JPanel PanelTabla;
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JLabel TextoActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
